version: "3.7"
services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-online-study-room
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    stdin_open: true
